# https://github.com/healeycodes/websocket-benchmarker/

language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements.txt

script:
  - ls
  - chmod +x test_bench.py
  - ./test_bench.py
